json.restaurant_id          food.restaurant_id
json.food_id                food.id
json.description            food.description
json.dish                   food.dish
json.fruits                 food.fruits
json.ingredient             food.ingredient
json.measurement            food.measurement
json.spice                  food.spice
json.sushi                  food.sushi
json.vegetables             food.vegetables